### ISSUE TITLE
Token

### ISSUE THREAD

**Issue by stefdewilde** [bartjanisse/node-red-contrib_BRP069C4#1]
Hello,

where did you get the token from?
Can you control your daikin airco with this node red?

Greetings
Stef

**Comment by bartjanisse** [comment]
Hi Stef,

Please read the discussion at https://github.com/cbrandlehner/homebridge-daikin-local/issues/123

Here you can find out how to get the token. And yes you can control the Daikin.

Please note that all is experimental!!!

Met vriendelijke groet,

Bart Janisse

Op 1 jul. 2021 om 20:13 heeft stefd ***@***.***> het volgende geschreven:

﻿

Hello,

where did you get the token from?
Can you control your daikin airco with this node red?

Greetings
Stef
